"""CME Group futures contract specifications used by the GUI calculator.

The dataset below focuses on providing enough information for position sizing:
symbol, official name, product group, tick size and tick value.  The figures were
compiled from the CME Group product slate and micro-product announcements that
were current as of late 2025.  Tick values are expressed in U.S. dollars.

This module intentionally keeps the data in plain Python so users can extend or
adjust the specifications without needing an additional data source.  The GUI
imports the ``CONTRACT_SPECS`` dictionary to populate the drop-down list and to
prefill the tick value whenever a user changes the selected product.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List


@dataclass(frozen=True)
class ContractSpec:
    """Minimal contract information for sizing calculations."""

    symbol: str
    name: str
    exchange: str
    product_group: str
    tick_size: float
    tick_value: float
    contract_unit: str
    is_micro: bool = False
    notes: str = ""

    @property
    def display(self) -> str:
        """Formatted label used in the combobox."""

        return f"{self.symbol} – {self.name} ({self.exchange})"


def _build_specs() -> Dict[str, ContractSpec]:
    specs: List[ContractSpec] = [
        # Equity index futures
        ContractSpec(
            "ES",
            "E-mini S&P 500",
            "CME",
            "Equity Index",
            tick_size=0.25,
            tick_value=12.50,
            contract_unit="50 x S&P 500 Index",
        ),
        ContractSpec(
            "MES",
            "Micro E-mini S&P 500",
            "CME",
            "Equity Index",
            tick_size=0.25,
            tick_value=1.25,
            contract_unit="5 x S&P 500 Index",
            is_micro=True,
        ),
        ContractSpec(
            "NQ",
            "E-mini Nasdaq-100",
            "CME",
            "Equity Index",
            tick_size=0.25,
            tick_value=5.00,
            contract_unit="20 x Nasdaq-100 Index",
        ),
        ContractSpec(
            "MNQ",
            "Micro E-mini Nasdaq-100",
            "CME",
            "Equity Index",
            tick_size=0.25,
            tick_value=0.50,
            contract_unit="2 x Nasdaq-100 Index",
            is_micro=True,
        ),
        ContractSpec(
            "YM",
            "E-mini Dow ($5)",
            "CBOT",
            "Equity Index",
            tick_size=1.0,
            tick_value=5.00,
            contract_unit="$5 x Dow Jones Industrial Average",
        ),
        ContractSpec(
            "MYM",
            "Micro E-mini Dow",
            "CBOT",
            "Equity Index",
            tick_size=1.0,
            tick_value=0.50,
            contract_unit="$0.50 x Dow Jones Industrial Average",
            is_micro=True,
        ),
        ContractSpec(
            "RTY",
            "E-mini Russell 2000",
            "CME",
            "Equity Index",
            tick_size=0.1,
            tick_value=5.00,
            contract_unit="50 x Russell 2000 Index",
        ),
        ContractSpec(
            "M2K",
            "Micro E-mini Russell 2000",
            "CME",
            "Equity Index",
            tick_size=0.1,
            tick_value=0.50,
            contract_unit="5 x Russell 2000 Index",
            is_micro=True,
        ),
        ContractSpec(
            "EMD",
            "E-mini S&P MidCap 400",
            "CME",
            "Equity Index",
            tick_size=0.1,
            tick_value=10.00,
            contract_unit="100 x S&P MidCap 400 Index",
        ),
        ContractSpec(
            "NKD",
            "Nikkei 225 (USD)",
            "CME",
            "Equity Index",
            tick_size=5.0,
            tick_value=25.00,
            contract_unit="$5 x Nikkei 225 Index",
        ),
        ContractSpec(
            "NIY",
            "Nikkei 225 (JPY)",
            "CME",
            "Equity Index",
            tick_size=5.0,
            tick_value=12.50,
            contract_unit="¥500 x Nikkei 225 Index",
        ),
        # Cryptocurrency futures
        ContractSpec(
            "BTC",
            "Bitcoin",
            "CME",
            "Cryptocurrency",
            tick_size=5.0,
            tick_value=25.00,
            contract_unit="5 bitcoin",
        ),
        ContractSpec(
            "MBT",
            "Micro Bitcoin",
            "CME",
            "Cryptocurrency",
            tick_size=5.0,
            tick_value=0.50,
            contract_unit="0.1 bitcoin",
            is_micro=True,
        ),
        ContractSpec(
            "ETH",
            "Ether",
            "CME",
            "Cryptocurrency",
            tick_size=0.25,
            tick_value=12.50,
            contract_unit="50 ether",
        ),
        ContractSpec(
            "MET",
            "Micro Ether",
            "CME",
            "Cryptocurrency",
            tick_size=0.25,
            tick_value=0.025,
            contract_unit="0.1 ether",
            is_micro=True,
        ),
        # Energy (NYMEX)
        ContractSpec(
            "CL",
            "WTI Crude Oil",
            "NYMEX",
            "Energy",
            tick_size=0.01,
            tick_value=10.00,
            contract_unit="1,000 barrels",
        ),
        ContractSpec(
            "QM",
            "E-mini Crude Oil",
            "NYMEX",
            "Energy",
            tick_size=0.025,
            tick_value=12.50,
            contract_unit="500 barrels",
        ),
        ContractSpec(
            "MCL",
            "Micro WTI Crude Oil",
            "NYMEX",
            "Energy",
            tick_size=0.01,
            tick_value=1.00,
            contract_unit="100 barrels",
            is_micro=True,
        ),
        ContractSpec(
            "NG",
            "Henry Hub Natural Gas",
            "NYMEX",
            "Energy",
            tick_size=0.001,
            tick_value=10.00,
            contract_unit="10,000 mmBtu",
        ),
        ContractSpec(
            "QG",
            "E-mini Natural Gas",
            "NYMEX",
            "Energy",
            tick_size=0.005,
            tick_value=12.50,
            contract_unit="2,500 mmBtu",
        ),
        ContractSpec(
            "MNG",
            "Micro Henry Hub Natural Gas",
            "NYMEX",
            "Energy",
            tick_size=0.001,
            tick_value=1.00,
            contract_unit="1,000 mmBtu",
            is_micro=True,
        ),
        ContractSpec(
            "RB",
            "RBOB Gasoline",
            "NYMEX",
            "Energy",
            tick_size=0.0001,
            tick_value=4.20,
            contract_unit="42,000 gallons",
        ),
        ContractSpec(
            "HO",
            "NY Harbor ULSD (Heating Oil)",
            "NYMEX",
            "Energy",
            tick_size=0.0001,
            tick_value=4.20,
            contract_unit="42,000 gallons",
        ),
        ContractSpec(
            "BZ",
            "Brent Crude Oil",
            "NYMEX",
            "Energy",
            tick_size=0.01,
            tick_value=10.00,
            contract_unit="1,000 barrels",
        ),
        # Metals (COMEX)
        ContractSpec(
            "GC",
            "Gold",
            "COMEX",
            "Metals",
            tick_size=0.1,
            tick_value=10.00,
            contract_unit="100 troy ounces",
        ),
        ContractSpec(
            "MGC",
            "Micro Gold",
            "COMEX",
            "Metals",
            tick_size=0.1,
            tick_value=1.00,
            contract_unit="10 troy ounces",
            is_micro=True,
        ),
        ContractSpec(
            "QO",
            "E-mini Gold",
            "COMEX",
            "Metals",
            tick_size=0.25,
            tick_value=12.50,
            contract_unit="50 troy ounces",
        ),
        ContractSpec(
            "SI",
            "Silver",
            "COMEX",
            "Metals",
            tick_size=0.005,
            tick_value=25.00,
            contract_unit="5,000 troy ounces",
        ),
        ContractSpec(
            "SIL",
            "Micro Silver",
            "COMEX",
            "Metals",
            tick_size=0.005,
            tick_value=5.00,
            contract_unit="1,000 troy ounces",
            is_micro=True,
        ),
        ContractSpec(
            "HG",
            "Copper",
            "COMEX",
            "Metals",
            tick_size=0.0005,
            tick_value=12.50,
            contract_unit="25,000 pounds",
        ),
        ContractSpec(
            "QC",
            "E-mini Copper",
            "COMEX",
            "Metals",
            tick_size=0.0005,
            tick_value=6.25,
            contract_unit="12,500 pounds",
        ),
        ContractSpec(
            "PL",
            "Platinum",
            "NYMEX",
            "Metals",
            tick_size=0.1,
            tick_value=5.00,
            contract_unit="50 troy ounces",
        ),
        ContractSpec(
            "PA",
            "Palladium",
            "NYMEX",
            "Metals",
            tick_size=0.1,
            tick_value=10.00,
            contract_unit="100 troy ounces",
        ),
        # Agricultural (CBOT/CME)
        ContractSpec(
            "ZC",
            "Corn",
            "CBOT",
            "Agriculture",
            tick_size=0.25,
            tick_value=12.50,
            contract_unit="5,000 bushels",
        ),
        ContractSpec(
            "ZS",
            "Soybeans",
            "CBOT",
            "Agriculture",
            tick_size=0.25,
            tick_value=12.50,
            contract_unit="5,000 bushels",
        ),
        ContractSpec(
            "ZW",
            "Chicago Wheat",
            "CBOT",
            "Agriculture",
            tick_size=0.25,
            tick_value=12.50,
            contract_unit="5,000 bushels",
        ),
        ContractSpec(
            "KE",
            "KC Hard Red Winter Wheat",
            "KC Board of Trade",
            "Agriculture",
            tick_size=0.25,
            tick_value=12.50,
            contract_unit="5,000 bushels",
        ),
        ContractSpec(
            "ZO",
            "Oats",
            "CBOT",
            "Agriculture",
            tick_size=0.25,
            tick_value=12.50,
            contract_unit="5,000 bushels",
        ),
        ContractSpec(
            "ZR",
            "Rough Rice",
            "CBOT",
            "Agriculture",
            tick_size=0.005,
            tick_value=10.00,
            contract_unit="2,000 cwt",
        ),
        ContractSpec(
            "ZM",
            "Soybean Meal",
            "CBOT",
            "Agriculture",
            tick_size=0.1,
            tick_value=10.00,
            contract_unit="100 short tons",
        ),
        ContractSpec(
            "ZL",
            "Soybean Oil",
            "CBOT",
            "Agriculture",
            tick_size=0.0001,
            tick_value=6.00,
            contract_unit="60,000 pounds",
        ),
        ContractSpec(
            "GF",
            "Feeder Cattle",
            "CME",
            "Livestock",
            tick_size=0.00025,
            tick_value=12.50,
            contract_unit="50,000 pounds",
        ),
        ContractSpec(
            "LE",
            "Live Cattle",
            "CME",
            "Livestock",
            tick_size=0.00025,
            tick_value=10.00,
            contract_unit="40,000 pounds",
        ),
        ContractSpec(
            "HE",
            "Lean Hogs",
            "CME",
            "Livestock",
            tick_size=0.00025,
            tick_value=10.00,
            contract_unit="40,000 pounds",
        ),
        ContractSpec(
            "LBS",
            "Random Length Lumber",
            "CME",
            "Lumber",
            tick_size=0.1,
            tick_value=11.00,
            contract_unit="27,500 board feet",
        ),
        ContractSpec(
            "DC",
            "Class III Milk",
            "CME",
            "Dairy",
            tick_size=0.01,
            tick_value=20.00,
            contract_unit="200,000 pounds",
        ),
        ContractSpec(
            "DA",
            "Class IV Milk",
            "CME",
            "Dairy",
            tick_size=0.01,
            tick_value=20.00,
            contract_unit="200,000 pounds",
        ),
        # Interest rates
        ContractSpec(
            "SR3",
            "3-Month SOFR",
            "CME",
            "Interest Rates",
            tick_size=0.0025,
            tick_value=6.25,
            contract_unit="$2,500 x (100 - rate)",
        ),
        ContractSpec(
            "GE",
            "Eurodollar",
            "CME",
            "Interest Rates",
            tick_size=0.0025,
            tick_value=6.25,
            contract_unit="$2,500 x (100 - rate)",
        ),
        ContractSpec(
            "ZB",
            "U.S. Treasury Bond",
            "CBOT",
            "Interest Rates",
            tick_size=0.03125,
            tick_value=31.25,
            contract_unit="$100,000 face value",
        ),
        ContractSpec(
            "UB",
            "Ultra U.S. Treasury Bond",
            "CBOT",
            "Interest Rates",
            tick_size=0.03125,
            tick_value=31.25,
            contract_unit="$100,000 face value",
        ),
        ContractSpec(
            "ZN",
            "10-Year T-Note",
            "CBOT",
            "Interest Rates",
            tick_size=0.015625,
            tick_value=15.625,
            contract_unit="$100,000 face value",
        ),
        ContractSpec(
            "TN",
            "Ultra 10-Year T-Note",
            "CBOT",
            "Interest Rates",
            tick_size=0.015625,
            tick_value=15.625,
            contract_unit="$100,000 face value",
        ),
        ContractSpec(
            "ZF",
            "5-Year T-Note",
            "CBOT",
            "Interest Rates",
            tick_size=0.0078125,
            tick_value=7.8125,
            contract_unit="$100,000 face value",
        ),
        ContractSpec(
            "ZT",
            "2-Year T-Note",
            "CBOT",
            "Interest Rates",
            tick_size=0.0078125,
            tick_value=7.8125,
            contract_unit="$200,000 face value",
        ),
        ContractSpec(
            "ZQ",
            "30-Day Fed Funds",
            "CME",
            "Interest Rates",
            tick_size=0.0025,
            tick_value=10.42,
            contract_unit="$4,167 x (100 - rate)",
        ),
        # FX majors
        ContractSpec(
            "6A",
            "Australian Dollar",
            "CME",
            "FX",
            tick_size=0.0001,
            tick_value=10.00,
            contract_unit="100,000 AUD",
        ),
        ContractSpec(
            "M6A",
            "Micro Australian Dollar",
            "CME",
            "FX",
            tick_size=0.0001,
            tick_value=1.00,
            contract_unit="10,000 AUD",
            is_micro=True,
        ),
        ContractSpec(
            "6B",
            "British Pound",
            "CME",
            "FX",
            tick_size=0.0001,
            tick_value=6.25,
            contract_unit="62,500 GBP",
        ),
        ContractSpec(
            "M6B",
            "Micro British Pound",
            "CME",
            "FX",
            tick_size=0.0001,
            tick_value=0.625,
            contract_unit="6,250 GBP",
            is_micro=True,
        ),
        ContractSpec(
            "6C",
            "Canadian Dollar",
            "CME",
            "FX",
            tick_size=0.0001,
            tick_value=10.00,
            contract_unit="100,000 CAD",
        ),
        ContractSpec(
            "M6C",
            "Micro Canadian Dollar",
            "CME",
            "FX",
            tick_size=0.0001,
            tick_value=1.00,
            contract_unit="10,000 CAD",
            is_micro=True,
        ),
        ContractSpec(
            "6E",
            "Euro FX",
            "CME",
            "FX",
            tick_size=0.00005,
            tick_value=6.25,
            contract_unit="125,000 EUR",
        ),
        ContractSpec(
            "M6E",
            "Micro Euro FX",
            "CME",
            "FX",
            tick_size=0.00005,
            tick_value=0.625,
            contract_unit="12,500 EUR",
            is_micro=True,
        ),
        ContractSpec(
            "6J",
            "Japanese Yen",
            "CME",
            "FX",
            tick_size=0.0000005,
            tick_value=6.25,
            contract_unit="12,500,000 JPY",
        ),
        ContractSpec(
            "M6J",
            "Micro Japanese Yen",
            "CME",
            "FX",
            tick_size=0.0000005,
            tick_value=0.625,
            contract_unit="1,250,000 JPY",
            is_micro=True,
        ),
        ContractSpec(
            "6M",
            "Mexican Peso",
            "CME",
            "FX",
            tick_size=0.0001,
            tick_value=5.00,
            contract_unit="500,000 MXN",
        ),
        ContractSpec(
            "M6M",
            "Micro Mexican Peso",
            "CME",
            "FX",
            tick_size=0.0001,
            tick_value=0.50,
            contract_unit="50,000 MXN",
            is_micro=True,
        ),
        ContractSpec(
            "6N",
            "New Zealand Dollar",
            "CME",
            "FX",
            tick_size=0.0001,
            tick_value=10.00,
            contract_unit="100,000 NZD",
        ),
        ContractSpec(
            "M6N",
            "Micro New Zealand Dollar",
            "CME",
            "FX",
            tick_size=0.0001,
            tick_value=1.00,
            contract_unit="10,000 NZD",
            is_micro=True,
        ),
        ContractSpec(
            "6S",
            "Swiss Franc",
            "CME",
            "FX",
            tick_size=0.0001,
            tick_value=12.50,
            contract_unit="125,000 CHF",
        ),
        ContractSpec(
            "M6S",
            "Micro Swiss Franc",
            "CME",
            "FX",
            tick_size=0.0001,
            tick_value=1.25,
            contract_unit="12,500 CHF",
            is_micro=True,
        ),
        ContractSpec(
            "6R",
            "Brazilian Real",
            "CME",
            "FX",
            tick_size=0.0001,
            tick_value=10.00,
            contract_unit="100,000 BRL",
        ),
        ContractSpec(
            "6Z",
            "South African Rand",
            "CME",
            "FX",
            tick_size=0.0001,
            tick_value=5.00,
            contract_unit="500,000 ZAR",
        ),
        ContractSpec(
            "6L",
            "Israeli Shekel",
            "CME",
            "FX",
            tick_size=0.0001,
            tick_value=10.00,
            contract_unit="100,000 ILS",
        ),
        ContractSpec(
            "6U",
            "Russian Ruble",
            "CME",
            "FX",
            tick_size=0.0001,
            tick_value=10.00,
            contract_unit="2,500,000 RUB",
        ),
    ]
    return {spec.symbol: spec for spec in specs}


CONTRACT_SPECS: Dict[str, ContractSpec] = _build_specs()

DEFAULT_CONTRACT = "MES"


def ordered_contract_displays() -> List[str]:
    """Return the drop-down values grouped by product type then symbol."""

    return [
        spec.display
        for spec in sorted(
            CONTRACT_SPECS.values(),
            key=lambda spec: (spec.product_group, spec.is_micro, spec.symbol),
        )
    ]


DISPLAY_TO_SYMBOL = {spec.display: spec.symbol for spec in CONTRACT_SPECS.values()}

